Discord Presence
cameroncros/OctoPrint-DiscordRemote pull request #150
Opened 2020-10-14 20:44 UTC by OctopusProteins

- Added support for a presence message as described in #90 and #142 .
- Added relevant settings for the presence cycler

Let me know if you need me to modify anything.

2020-10-14 23:04 UTC, cameroncros requested changes

2020-10-14 23:04 UTC, cameroncros commented on octoprint_discordremote/presence.py
> +                self.discord.update_presence(presence_cycle[self.presence_cycle_id])
```suggestion
                self.discord.update_presence(presence_cycle[self.presence_cycle_id % len(presense_cycle)])
```

2020-10-14 23:04 UTC, cameroncros commented on octoprint_discordremote/presence.py
> +            for i in range(int(round(int(self.plugin.get_settings().get(['presence_cycle_time']))))):
What is this int(round(int( stuff?
```suggestion
            for i in range(int(self.plugin.get_settings().get(['presence_cycle_time']))):
```

2020-10-15 00:24 UTC, OctopusProteins commented on octoprint_discordremote/presence.py
> +                self.discord.update_presence(presence_cycle[self.presence_cycle_id])
fixed by https://github.com/cameroncros/OctoPrint-DiscordRemote/pull/150/commits/a573705849abc9f4ca783c856f7126049ccd9cee

2020-10-17 02:12 UTC, OctopusProteins commented
Made the changes you requested, Anything else?

2020-10-18 12:02 UTC, cameroncros commented on octoprint_discordremote/presence.py
> +                self.discord.update_presence(presence_cycle[self.presence_cycle_id] % len(presence_cycle))
```suggestion
                self.discord.update_presence(presence_cycle[self.presence_cycle_id % len(presence_cycle)])
```

2020-10-18 12:05 UTC, cameroncros approved these changes

2020-10-18 12:05 UTC, merged